FROM wwwthoughtworks/build-your-own-radar:latest

WORKDIR /src/build-your-own-radar
RUN npm run build:prod

RUN mkdir -p /opt/build-your-own-radar
WORKDIR /opt/build-your-own-radar
RUN cp -r /src/build-your-own-radar/dist/* ./
RUN mkdir -p files
RUN cp /src/build-your-own-radar/spec/end_to_end_tests/resources/localfiles/* ./files/
RUN cp /src/build-your-own-radar/default.template /etc/nginx/conf.d/default.conf

CMD nginx -g 'daemon off;'
