FROM node:18 AS build

ARG SHEET_ID
ARG SHEET_NAME

WORKDIR /src
RUN git clone https://github.com/avengerpenguin/build-your-own-radar.git
WORKDIR /src/build-your-own-radar
RUN npm install

RUN npm test && ASSET_PATH=/radar/ npm run build:prod
RUN sed -i 's|/images/|images|g' dist/index.html

FROM scratch as output

COPY --from=build /src/build-your-own-radar/dist /
